
DROP TABLE IF EXISTS TAREFA;
DROP TABLE IF EXISTS PROJETO;

CREATE TABLE PROJETO (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    descricao VARCHAR(255),
    data_criacao TIMESTAMP
);

CREATE TABLE TAREFA (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(50) NOT NULL,
    descricao VARCHAR(255),
    status VARCHAR(20) NOT NULL,
    prioridade VARCHAR(20) NOT NULL,
    projeto_id BIGINT,
    CONSTRAINT fk_projeto FOREIGN KEY (projeto_id) REFERENCES projeto(id) ON DELETE CASCADE
);
